import sqlite3

with sqlite3.connect("baza.db") as connection:
    c = connection.cursor()
    c.execute("""DROP TABLE posts""")
    c.execute("CREATE TABLE posts(Przepis TEXT, Składniki TEXT)")
    c.execute('INSERT INTO posts VALUES("Gołąbki z młodej kapusty", "kapusta, ryż, kasza, mięlona wieprzowina, cebula, sos sojowy, ocet balsamiczny, bulion, przecier pomidorowy, mąka, słodka śmietanka, koperek")')
    c.execute('INSERT INTO posts VALUES("Pierogi ruskie", "ziemniaki, ser biały, cebula, mąka, masło")')
    c.execute('INSERT INTO posts VALUES("Kotlet Pożarski", "bułka kajzerka, mleko, chleb tostowy, pierś kurczaka, słodka śmietanka, oliwa z oliwek")')
    c.execute('INSERT INTO posts VALUES("Zapiekanka makaronowa z kurczakiem, brokułami i szpinakiem", "pierś kurczaka, czosnek, oliwa z oliwek, makaron, brokuł, szpinak, masło, parmezan, mleko, serek typu Philadelphia")')
    c.execute('INSERT INTO posts VALUES("Kurczak w kremowym sosie z dynią i marchewką", "pierś kurczaka, marchewka, mąka, dynia, cebula, bulion, słodka śmietanka, oliwa z oliwek, natka pietruszki")')
    c.execute('INSERT INTO posts VALUES("Zupa z cukinią i kurczakiem", "ziemniaki, cukinia, marchewka, pierś kurczaka, cebula, oliwa z oliwek, masło, bulion, śmietana, szczypiorek, natka pietruszki")')
    c.execute('INSERT INTO posts VALUES("Gulasz drobiowy z piersi kurczaka", "pierś kurczaka, oliwa z oliwek, papryka, cebula, czosnek, bulion, przecier pomidorowy, masło, koncentrat pomidorowy")')
    c.execute('INSERT INTO posts VALUES("Filet z kurczaka zapiekane z pesto, pomidorem i mozzarellą", "pierś kurczaka, mozzarella, pomidor, pesto, oliwa z oliwek, bazylia")')
    c.execute('INSERT INTO posts VALUES("Zupa pieczarkowa", "masło, cebula, pieczarki, bulion, bazylia, słodka śmietanka")')
    c.execute('INSERT INTO posts VALUES("Zupa szpinakowa", "masło, oliwa z oliwek, cebula, por, ziemniaki, bulion, czosnek, szpinak, słodka śmietanka")')
    c.execute('INSERT INTO posts VALUES("Zupa botwinka", "marchewka, pietruszka, bulion, botwinka, buraczki, mąka, śmietana, masło, cytryna")')
    c.execute('INSERT INTO posts VALUES("Zupa fasolowa", "fasola biała, żeberka wieprzowe, wędzony boczek, marchewka, pietruszka, seler, cebula, czosnek, ziemniaki")')
    c.execute('INSERT INTO posts VALUES("Zupa Marchewkowa", "cebula, oliwa z oliwek, marchewka, pietruszka, imbir, bulion, słodka śmietanka, soczewica, czosnek, natka pietruszki")')
    c.execute('INSERT INTO posts VALUES("Zupa gulaszowa", "cebula, czosnek, masło, łopatka wieprzowa, białe wino, bulion, papryka, ziemniaki, pomidory, koncentrat pomidorowy, natka pietruszki")')
    c.execute('INSERT INTO posts VALUES("Zupa brokułowa", "brokuł, ziemniaki, marchewka, cebula, por, masło, oliwa z oliwek, bulion, śmietana, serek topiony, bazylia, szczypiorek")')
    c.execute('INSERT INTO posts VALUES("Zupa szczawiowa", "żeberka wieprzowe, szyja indycza, marchewka, pietruszka, por, seler, cebula, szczaw, śmietana, mąka")')
    c.execute('INSERT INTO posts VALUES("Zupa jarzynowa", "marchewka, ziemniaki, fasolka szparagowa, kalafior, cebula, masło, oliwa z oliwek, bulion, śmietana, natka pietruszki, bazylia")')
    c.execute('INSERT INTO posts VALUES("Zupa grzybowa", "masło, oliwa z oliwek, cebula, ziemniaki, grzyby, białe wino, bulion, natka pietruszki, śmietana")')
    c.execute('INSERT INTO posts VALUES("Wieprzowina po chińsku", "polędwica wieprzowa, mąka ziemniaczana, papryka, cebula, marchewka, por, czosnek, papryczka chili, imbir, olej kokosowy, ryż, szczypiorek, ocet ryżowy, sos sojowy, brązowy cukier")')
    c.execute('INSERT INTO posts VALUES("Kanapka z pulled pork", "bułka, pulled pork, kiszony ogórek, majonez, ketchup, kapusta pekińska, szczypiorek, natka pietruszki")')
    c.execute('INSERT INTO posts VALUES("Pasztet", "wieprzowina, wołowina, boczek, cebula, bułka, wątróbka, jajko, słonina, bułka tarta, smalec")')
